"""add_difficulty_to_quiz_questions

Revision ID: 01b1555ca7c2
Revises: 15fe7d803359
Create Date: 2026-02-22 21:30:08.890461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b1555ca7c2'
down_revision: Union[str, None] = '15fe7d803359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('difficulty', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'difficulty')
    # ### end Alembic commands ###
